name: Visual Debugger CI

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

defaults:
  run:
    working-directory: ./visual-debugger

jobs:
  vdb-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: "npm install -f"

      - name: Run svelte-check
        continue-on-error: true
        run: "npm run check"

      - name: Run unit tests
        continue-on-error: true
        run: "npm run test:unit"

      # - name: Run integration tests
      #   continue-on-error: true
      #   run: "npm run test:integration"
